-------------------|
--MARIO BROS. SQL--|
-------------------|

---------------------------|
--ESTRUCTURA (TABLAS) DDL--|
---------------------------|

DROP TABLE TMP_NUMBERS;

DROP TABLE SER_BONIFICACION;
DROP TABLE SER_REVANCHA;
DROP TABLE DESAFIAR_EN;
DROP TABLE SER_COMPATIBLE;
DROP TABLE TENER_POSICION_SUPERIOR;
DROP TABLE DESBLOQUEAR_MEDIANTE;
DROP TABLE APARECER;
DROP TABLE JEFE;
DROP TABLE REINO;
DROP TABLE PERSONAJES;
DROP TABLE ENCONTRARSE_EN;
DROP TABLE PROPORCIONAR;
DROP TABLE HABILIDADES;
DROP TABLE TEMPORALES;
DROP TABLE BENEFICIOSOS;
DROP TABLE POWER_UPS;
DROP TABLE COLECCIONABLES;
DROP TABLE MONEDAS;
DROP TABLE OBJETOS;
DROP TABLE DESBLOQUEAR;
DROP TABLE META;
DROP TABLE PUNTOS_GUARDADO;
DROP TABLE BONUS;
DROP TABLE NIVEL_JEFE;
DROP TABLE MISIONES;
DROP TABLE NIVELES;
DROP TABLE MUNDOS;
DROP TABLE ESCENARIO;
DROP TABLE SALIR_EN;
DROP TABLE PAISES;
DROP TABLE CREARSE_PARA;
DROP TABLE PLATAFORMAS;
DROP TABLE BASARSE_EN;
DROP TABLE AVENTURAS;


CREATE TABLE AVENTURAS
(
    TITULO VARCHAR2(60) NOT NULL,
    PORTADA VARCHAR2(100), -- DIRECCIÓN IMAGEN (PROVISIONAL)
    ANYO NUMBER(4),
    DESCRIPCION VARCHAR2(300),
    OBJETIVO VARCHAR2(100),
    IMPLEMENTACION VARCHAR2(200),
    TITULO_REMAKE VARCHAR2(60),
    CONSTRAINT PK_AVENTURAS PRIMARY KEY(TITULO),
    CONSTRAINT FK_AVENTURAS_AVENTURAS FOREIGN KEY(TITULO_REMAKE)
        REFERENCES AVENTURAS(TITULO)
);

CREATE TABLE BASARSE_EN
(
    TITULO_AVENTURA VARCHAR2(60) NOT NULL,
    TITULO_REFERENTE VARCHAR2(60) NOT NULL,
    REFERENCIA VARCHAR2(50),
    CONSTRAINT PK_BASARSE_EN PRIMARY KEY
        (TITULO_AVENTURA, TITULO_REFERENTE),
    CONSTRAINT FK_BASARSE_EN_AVENTURAS FOREIGN KEY(TITULO_AVENTURA)
        REFERENCES AVENTURAS(TITULO),
    CONSTRAINT FK_BASARSE_EN_AVENTURAS_REF FOREIGN KEY(TITULO_REFERENTE)
        REFERENCES AVENTURAS(TITULO)
);

CREATE TABLE PLATAFORMAS
(
    NOMBRE VARCHAR2(60) NOT NULL,
    POTENCIA NUMBER(9,4), --GHz
    CONSTRAINT PK_PLATAFORMAS PRIMARY KEY(NOMBRE)
);

CREATE TABLE CREARSE_PARA
(
    TITULO_AVENTURA VARCHAR2(60) NOT NULL,
    NOMBRE_PLATAFORMA VARCHAR2(60) NOT NULL,
    CONSTRAINT PK_CREARSE_PARA PRIMARY KEY
        (TITULO_AVENTURA, NOMBRE_PLATAFORMA),
    CONSTRAINT FK_CREARSE_PARA_AVENTURAS FOREIGN KEY(TITULO_AVENTURA)
        REFERENCES AVENTURAS(TITULO),
    CONSTRAINT FK_CREARSE_PARA_PLATAFORMAS FOREIGN KEY(NOMBRE_PLATAFORMA)
        REFERENCES PLATAFORMAS(NOMBRE)
);

CREATE TABLE PAISES
(
    NOMBRE VARCHAR2(60) NOT NULL,
    SEGUIDORES NUMBER(8),
    CRITICA NUMBER(4,2),
    CONSTRAINT PK_PAISES PRIMARY KEY (NOMBRE)
);

CREATE TABLE SALIR_EN
(
    NOMBRE_PAIS VARCHAR2(60) NOT NULL,
    TITULO_AVENTURA VARCHAR2(60) NOT NULL,
    NOMBRE_PLATAFORMA VARCHAR2(60) NOT NULL,
    FECHA_SALIDA DATE,
    CONSTRAINT PK_SALIR_EN PRIMARY KEY 
        (NOMBRE_PAIS, TITULO_AVENTURA, NOMBRE_PLATAFORMA),
    CONSTRAINT FK_SALIR_EN_PAISES FOREIGN KEY (NOMBRE_PAIS)
        REFERENCES PAISES(NOMBRE),
    CONSTRAINT FK_SALIR_EN_CREARSE_PARA FOREIGN KEY 
        (TITULO_AVENTURA, NOMBRE_PLATAFORMA)
        REFERENCES CREARSE_PARA(TITULO_AVENTURA, NOMBRE_PLATAFORMA)
);

CREATE TABLE ESCENARIO
(
    NOMBRE VARCHAR2(60) NOT NULL,
    DESCRIPCION VARCHAR2(300),
    CONSTRAINT PK_ESCENARIO PRIMARY KEY(NOMBRE)
);

CREATE TABLE MUNDOS
(
    TITULO_AVENTURA VARCHAR2(60) NOT NULL,
    NUMERO NUMBER(3) NOT NULL,
    NOMBRE_ESCENARIO VARCHAR2(60) NOT NULL,
    TEMATICA VARCHAR2(30),
    CONSTRAINT PK_MUNDOS PRIMARY KEY(TITULO_AVENTURA, NUMERO),
    CONSTRAINT FK_MUNDOS_AVENTURAS FOREIGN KEY(TITULO_AVENTURA)
        REFERENCES AVENTURAS(TITULO),
    CONSTRAINT FK_MUNDOS_ESCENARIO FOREIGN KEY(NOMBRE_ESCENARIO)
        REFERENCES ESCENARIO(NOMBRE)
);

CREATE TABLE NIVELES
(
    TITULO_AVENTURA VARCHAR2(60) NOT NULL,
    NUMERO_MUNDO NUMBER(3) NOT NULL,
    NUMERO NUMBER(3) NOT NULL,
    NOMBRE VARCHAR2(60),
    CONSTRAINT PK_NIVELES PRIMARY KEY
        (TITULO_AVENTURA, NUMERO_MUNDO, NUMERO),
    CONSTRAINT FK_NIVELES_MUNDOS FOREIGN KEY
        (TITULO_AVENTURA, NUMERO_MUNDO)
        REFERENCES MUNDOS(TITULO_AVENTURA, NUMERO)
);

CREATE TABLE MISIONES
(
    TITULO_AVENTURA VARCHAR2(60) NOT NULL,
    NUMERO_MUNDO NUMBER(3) NOT NULL,
    NUMERO_NIVEL NUMBER(3) NOT NULL,
    DURACION_MAX NUMBER(5) NOT NULL,
    TIPO VARCHAR2(30),
    CONSTRAINT PK_MISIONES PRIMARY KEY
        (TITULO_AVENTURA, NUMERO_MUNDO, NUMERO_NIVEL),
    CONSTRAINT FK_MISIONES_NIVELES FOREIGN KEY
        (TITULO_AVENTURA, NUMERO_MUNDO, NUMERO_NIVEL)
        REFERENCES NIVELES(TITULO_AVENTURA, NUMERO_MUNDO, NUMERO)
);

CREATE TABLE NIVEL_JEFE
(
    TITULO_AVENTURA VARCHAR2(60) NOT NULL,
    NUMERO_MUNDO NUMBER(3) NOT NULL,
    NUMERO_NIVEL NUMBER(3) NOT NULL,
    FINAL NUMBER(1) DEFAULT 0 NOT NULL, 
    CONSTRAINT FIN_0_OR_1 CHECK (FINAL IN (1,0)),
    FORMA VARCHAR2(20),
    CONSTRAINT PK_NIVEL_JEFE PRIMARY KEY
        (TITULO_AVENTURA, NUMERO_MUNDO, NUMERO_NIVEL),
    CONSTRAINT FK_NIVEL_JEFE_MISIONES FOREIGN KEY
        (TITULO_AVENTURA, NUMERO_MUNDO, NUMERO_NIVEL)
        REFERENCES MISIONES(TITULO_AVENTURA, NUMERO_MUNDO, NUMERO_NIVEL)
);

CREATE TABLE BONUS
(
    TITULO_AVENTURA VARCHAR2(60) NOT NULL,
    NUMERO_MUNDO NUMBER(3) NOT NULL,
    NUMERO_NIVEL NUMBER(3) NOT NULL,
    RECOMPENSA_MAX VARCHAR2(100),
    TITULO_AVENTURA_MISION VARCHAR2(60),
    NUMERO_MUNDO_MISION  NUMBER(3),
    NUMERO_NIVEL_MISION  NUMBER(3),
    CONSTRAINT PK_BONUS PRIMARY KEY
        (TITULO_AVENTURA, NUMERO_MUNDO, NUMERO_NIVEL),
    CONSTRAINT FK_BONUS_NIVELES FOREIGN KEY
        (TITULO_AVENTURA, NUMERO_MUNDO, NUMERO_NIVEL)
        REFERENCES NIVELES(TITULO_AVENTURA, NUMERO_MUNDO, NUMERO),
    CONSTRAINT FK_BONUS_MISIONES FOREIGN KEY
        (TITULO_AVENTURA_MISION, NUMERO_MUNDO_MISION, 
            NUMERO_NIVEL_MISION)
        REFERENCES MISIONES(TITULO_AVENTURA, NUMERO_MUNDO, NUMERO_NIVEL)
);

CREATE TABLE PUNTOS_GUARDADO
(
    TITULO_AVENTURA VARCHAR2(60) NOT NULL,
    NUMERO_MUNDO NUMBER(3) NOT NULL,
    NUMERO_NIVEL NUMBER(3) NOT NULL,
    NUMERO NUMBER(2) NOT NULL,
    UBICACION_X NUMBER(7,3),
    UBICACION_Y NUMBER(7,3),
    UBICACION_Z NUMBER(7,3),
    CONSTRAINT PK_PUNTOS_GUARDADO PRIMARY KEY
        (TITULO_AVENTURA, NUMERO_MUNDO, NUMERO_NIVEL, NUMERO),
    CONSTRAINT FK_PUNTOS_GUARDADO_MISIONES FOREIGN KEY
        (TITULO_AVENTURA, NUMERO_MUNDO, NUMERO_NIVEL)
        REFERENCES MISIONES(TITULO_AVENTURA, NUMERO_MUNDO, 
            NUMERO_NIVEL)
);

CREATE TABLE META
(
    TITULO_AVENTURA VARCHAR2(60) NOT NULL,
    NUMERO_MUNDO NUMBER(3) NOT NULL,
    NUMERO_NIVEL NUMBER(3) NOT NULL,
    NUMERO_GUARDADO NUMBER(2) NOT NULL,
    FORMA VARCHAR2(30),
    CONSTRAINT PK_META PRIMARY KEY
        (TITULO_AVENTURA, NUMERO_MUNDO, NUMERO_NIVEL, 
            NUMERO_GUARDADO),
    CONSTRAINT FK_META_PUNTOS_GUARDADO FOREIGN KEY
        (TITULO_AVENTURA, NUMERO_MUNDO, NUMERO_NIVEL, 
            NUMERO_GUARDADO)
        REFERENCES PUNTOS_GUARDADO(TITULO_AVENTURA, NUMERO_MUNDO, 
            NUMERO_NIVEL, NUMERO)
);

CREATE TABLE DESBLOQUEAR
(
    TITULO_AVENTURA_META VARCHAR2(60) NOT NULL,
    NUMERO_MUNDO_META NUMBER(3) NOT NULL,
    NUMERO_NIVEL_META NUMBER(3) NOT NULL,
    NUMERO_GUARDADO_META NUMBER(2) NOT NULL,
    TITULO_AVENTURA_NIVEL VARCHAR2(60) NOT NULL,
    NUMERO_MUNDO_NIVEL NUMBER(3) NOT NULL,
    NUMERO_NIVEL NUMBER(3) NOT NULL,
    CONSTRAINT PK_DESBLOQUEAR PRIMARY KEY
        (TITULO_AVENTURA_NIVEL, NUMERO_MUNDO_NIVEL, NUMERO_NIVEL),
    CONSTRAINT UK_DESBLOQUEAR UNIQUE 
        (TITULO_AVENTURA_META, NUMERO_MUNDO_META,
            NUMERO_NIVEL_META, NUMERO_GUARDADO_META),
    CONSTRAINT FK_DESBLOQUEAR_NIVELES FOREIGN KEY
        (TITULO_AVENTURA_NIVEL, NUMERO_MUNDO_NIVEL, NUMERO_NIVEL)
        REFERENCES NIVELES(TITULO_AVENTURA, NUMERO_MUNDO, NUMERO),
    CONSTRAINT FK_DESBLOQUEAR_META FOREIGN KEY 
        (TITULO_AVENTURA_META, NUMERO_MUNDO_META,
            NUMERO_NIVEL_META, NUMERO_GUARDADO_META)
        REFERENCES META(TITULO_AVENTURA, NUMERO_MUNDO,
            NUMERO_NIVEL, NUMERO_GUARDADO)
);

CREATE TABLE OBJETOS
(
    CODIGO VARCHAR2(4) NOT NULL,
    NOMBRE VARCHAR2(60),
    CONSTRAINT PK_OBJETOS PRIMARY KEY (CODIGO)
);

CREATE TABLE MONEDAS
(
    CODIGO_OBJETO VARCHAR2(4) NOT NULL,
    VALOR NUMBER(3),
    COLOR VARCHAR2(6), --HEXADECIMAL
    CONSTRAINT PK_MONEDAS PRIMARY KEY (CODIGO_OBJETO),
    CONSTRAINT FK_MONEDAS_OBJETOS FOREIGN KEY (CODIGO_OBJETO)
        REFERENCES OBJETOS(CODIGO)
);

CREATE TABLE COLECCIONABLES
(
    CODIGO_OBJETO VARCHAR2(4) NOT NULL,
    OBTENIDO NUMBER(1) DEFAULT 0 NOT NULL, 
    CONSTRAINT OBTENIDO_0_OR_1 CHECK (OBTENIDO IN ('1','0')),
    CONSTRAINT PK_COLECCIONABLES PRIMARY KEY (CODIGO_OBJETO),
    CONSTRAINT FK_COLECCIONABLES_OBJETOS FOREIGN KEY (CODIGO_OBJETO)
        REFERENCES OBJETOS(CODIGO)
);

CREATE TABLE POWER_UPS
(
    CODIGO_OBJETO VARCHAR2(4) NOT NULL,
    DESCRIPCION VARCHAR2(300),
    IMAGEN VARCHAR2(100), -- DIRECCIÓN IMAGEN (PROVISIONAL)
    CONSTRAINT PK_POWER_UPS PRIMARY KEY (CODIGO_OBJETO),
    CONSTRAINT FK_POWER_UPS_OBJETOS FOREIGN KEY (CODIGO_OBJETO)
        REFERENCES OBJETOS(CODIGO)
);

CREATE TABLE BENEFICIOSOS
(
    CODIGO_OBJETO VARCHAR2(4) NOT NULL,
    PODER NUMBER(3),
    CONSTRAINT PK_BENEFICIOSOS PRIMARY KEY (CODIGO_OBJETO),
    CONSTRAINT FK_BENEFICIOSOS_POWER_UPS FOREIGN KEY (CODIGO_OBJETO)
        REFERENCES POWER_UPS(CODIGO_OBJETO)
);

CREATE TABLE TEMPORALES
(
    CODIGO_OBJETO VARCHAR2(4) NOT NULL,
    DURACION NUMBER(4),
    CONSTRAINT PK_TEMPORALES PRIMARY KEY (CODIGO_OBJETO),
    CONSTRAINT FK_TEMPORALES_POWER_UPS FOREIGN KEY (CODIGO_OBJETO)
        REFERENCES POWER_UPS(CODIGO_OBJETO)
);

CREATE TABLE HABILIDADES
(
    NOMBRE VARCHAR2(60) NOT NULL,
    DESCRIPCION VARCHAR2(300),
    CONSTRAINT PK_HABILIDADES PRIMARY KEY (NOMBRE)
);
CREATE TABLE PROPORCIONAR
(
    NOMBRE_HABILIDAD VARCHAR2(60) NOT NULL,
    CODIGO_OBJETO_BENEFICIOSO VARCHAR2(4) NOT NULL,
    IMPLEMENTACION NUMBER(1),
    CONSTRAINT PK_PROPORCIONAR PRIMARY KEY 
        (CODIGO_OBJETO_BENEFICIOSO, NOMBRE_HABILIDAD),
    CONSTRAINT FK_PROPORCIONAR_HABILIDADES FOREIGN KEY (NOMBRE_HABILIDAD)
        REFERENCES HABILIDADES (NOMBRE),
    CONSTRAINT FK_PROPORCIONAR_BENEFICIOSOS FOREIGN KEY (CODIGO_OBJETO_BENEFICIOSO)
        REFERENCES BENEFICIOSOS (CODIGO_OBJETO)
);

CREATE TABLE ENCONTRARSE_EN
(
    CODIGO_OBJETO VARCHAR2(4) NOT NULL,
    TITULO_AVENTURA VARCHAR2(60) NOT NULL,
    NUMERO_MUNDO NUMBER(3) NOT NULL,
    NUMERO_NIVEL NUMBER(3) NOT NULL,
    CANTIDAD NUMBER(3),
    CONSTRAINT PK_ENCONTRARSE_EN PRIMARY KEY 
        (CODIGO_OBJETO, TITULO_AVENTURA, NUMERO_MUNDO, NUMERO_NIVEL),
    CONSTRAINT FK_ENCONTRARSE_EN_NIVELES FOREIGN KEY
        (TITULO_AVENTURA, NUMERO_MUNDO, NUMERO_NIVEL)
        REFERENCES NIVELES(TITULO_AVENTURA, NUMERO_MUNDO, NUMERO),
    CONSTRAINT FK_ENCONTRARSE_EN_OBJETOS FOREIGN KEY (CODIGO_OBJETO)
        REFERENCES OBJETOS(CODIGO)
);

CREATE TABLE PERSONAJES
(
    NOMBRE_JAP VARCHAR2(60) NOT NULL,
    NOMBRE_ESP VARCHAR2(60) NOT NULL,
    NOMBRE_ING VARCHAR2(60),
    IMAGEN VARCHAR2(100),
    RAZA VARCHAR2(60),
    BONDAD VARCHAR2(1) DEFAULT 'N' NOT NULL, 
    CONSTRAINT BONDAD_B_M_OR_N CHECK (BONDAD IN ('B','M','N')),
    NOMBRE_JAP_VERSION VARCHAR2(60),
    CONSTRAINT PK_PERSONAJES PRIMARY KEY (NOMBRE_JAP),
    CONSTRAINT UK_PERSONAJES UNIQUE (NOMBRE_ESP),
    CONSTRAINT FK_PERSONAJES_PERSONAJES FOREIGN KEY (NOMBRE_JAP_VERSION)
        REFERENCES PERSONAJES(NOMBRE_JAP)
);

CREATE TABLE REINO
(
    NOMBRE_JAP VARCHAR2(60) NOT NULL,
    NOMBRE_REINO VARCHAR2(60),
    CONSTRAINT PK_REINO PRIMARY KEY (NOMBRE_JAP),
    CONSTRAINT FK_REINO_PERSONAJES FOREIGN KEY (NOMBRE_JAP)
        REFERENCES PERSONAJES(NOMBRE_JAP)
);

CREATE TABLE JEFE
(
    NOMBRE_JAP VARCHAR2(60) NOT NULL,
    INTIMIDACION VARCHAR2(2),
    CONSTRAINT PK_JEFE PRIMARY KEY (NOMBRE_JAP),
    CONSTRAINT FK_JEFE_PERSONAJES FOREIGN KEY (NOMBRE_JAP)
        REFERENCES PERSONAJES(NOMBRE_JAP)
);

CREATE TABLE APARECER
(
    BANDO VARCHAR2(40),
    NOMBRE_PERSONAJE VARCHAR2(60) NOT NULL,
    TITULO_AVENTURA VARCHAR2(60) NOT NULL,
    CONSTRAINT PK_APARECER PRIMARY KEY 
        (NOMBRE_PERSONAJE, TITULO_AVENTURA),
    CONSTRAINT FK_APARECER_PERSONAJES FOREIGN KEY (NOMBRE_PERSONAJE)
        REFERENCES PERSONAJES (NOMBRE_JAP),
    CONSTRAINT FK_APARECER_AVENTURAS FOREIGN KEY (TITULO_AVENTURA)
        REFERENCES AVENTURAS (TITULO)
);

CREATE TABLE DESBLOQUEAR_MEDIANTE
(
    NOMBRE_PERSONAJE VARCHAR2(60) NOT NULL,
    CODIGO_OBJETO VARCHAR2(4) NOT NULL,
    CONSTRAINT PK_DESBLOQUEAR_MEDIANTE PRIMARY KEY 
        (CODIGO_OBJETO),
    CONSTRAINT UK_DESBLOQUEAR_MEDIANTE UNIQUE
        (NOMBRE_PERSONAJE),
    CONSTRAINT FK_DESBLOQUEAR_MEDIANTE_PER FOREIGN KEY (NOMBRE_PERSONAJE)
        REFERENCES PERSONAJES (NOMBRE_JAP),
    CONSTRAINT FK_DESBLOQUEAR_MEDIANTE_OBJ FOREIGN KEY (CODIGO_OBJETO)
        REFERENCES OBJETOS (CODIGO)
);

CREATE TABLE TENER_POSICION_SUPERIOR
(
    NOMBRE_PERSONAJE_SUPERIOR VARCHAR2(60) NOT NULL,
    NOMBRE_PERSONAJE_INFERIOR VARCHAR2(60) NOT NULL,
    CONSTRAINT PK_TENER_POSICION PRIMARY KEY 
        (NOMBRE_PERSONAJE_SUPERIOR, NOMBRE_PERSONAJE_INFERIOR),
    CONSTRAINT FK_TENER_POSICION_SUP FOREIGN KEY 
        (NOMBRE_PERSONAJE_SUPERIOR)
        REFERENCES REINO (NOMBRE_JAP),
    CONSTRAINT FK_TENER_POSICION_INF FOREIGN KEY 
        (NOMBRE_PERSONAJE_INFERIOR)
        REFERENCES REINO (NOMBRE_JAP)
);

CREATE TABLE SER_COMPATIBLE
(
    NOMBRE_PERSONAJE VARCHAR2(60) NOT NULL,
    CODIGO_OBJETO_BENEFICIOSO VARCHAR2(4) NOT NULL,
    TITULO_AVENTURA VARCHAR2(60) NOT NULL,
    IMAGEN VARCHAR2(100),
    CONSTRAINT PK_SER_COMPATIBLE PRIMARY KEY 
        (NOMBRE_PERSONAJE, CODIGO_OBJETO_BENEFICIOSO, TITULO_AVENTURA),
    CONSTRAINT FK_SER_COMPATIBLE_PERSONAJES FOREIGN KEY (NOMBRE_PERSONAJE)
        REFERENCES PERSONAJES (NOMBRE_JAP),
    CONSTRAINT FK_SER_COMPATIBLE_OBJETOS FOREIGN KEY (CODIGO_OBJETO_BENEFICIOSO)
        REFERENCES BENEFICIOSOS (CODIGO_OBJETO),
    CONSTRAINT FK_SER_COMPATIBLE_AVENTURAS FOREIGN KEY (TITULO_AVENTURA)
        REFERENCES AVENTURAS (TITULO)
);

CREATE TABLE DESAFIAR_EN
(
    TITULO_AVENTURA VARCHAR2(60) NOT NULL,
    NUMERO_MUNDO NUMBER(3) NOT NULL,
    NUMERO_NIVEL NUMBER(3) NOT NULL,
    NOMBRE_JEFE VARCHAR2(60) NOT NULL,
    DIFICULTAD NUMBER(1) NOT NULL,
    CONSTRAINT PK_DESAFIAR_EN PRIMARY KEY 
        (TITULO_AVENTURA, NUMERO_MUNDO, NUMERO_NIVEL, 
            NOMBRE_JEFE, DIFICULTAD),
    CONSTRAINT FK_DESAFIAR_EN_NIVEL_JEFE FOREIGN KEY 
        (TITULO_AVENTURA, NUMERO_MUNDO, NUMERO_NIVEL)
        REFERENCES NIVEL_JEFE (TITULO_AVENTURA, NUMERO_MUNDO, NUMERO_NIVEL),
    CONSTRAINT FK_DESAFIAR_EN_JEFE FOREIGN KEY (NOMBRE_JEFE)
        REFERENCES JEFE (NOMBRE_JAP)
);

CREATE TABLE SER_REVANCHA
(
    TITULO_AVENTURA_ANT VARCHAR2(60) NOT NULL,
    NUMERO_MUNDO_ANT NUMBER(3) NOT NULL,
    NUMERO_NIVEL_ANT NUMBER(3) NOT NULL,
    NOMBRE_JEFE_ANT VARCHAR2(60) NOT NULL,
    DIFICULTAD_ANT NUMBER(1) NOT NULL,
    TITULO_AVENTURA_REV VARCHAR2(60) NOT NULL,
    NUMERO_MUNDO_REV NUMBER(3) NOT NULL,
    NUMERO_NIVEL_REV NUMBER(3) NOT NULL,
    NOMBRE_JEFE_REV VARCHAR2(60) NOT NULL,
    DIFICULTAD_REV NUMBER(1) NOT NULL,
    CONSTRAINT PK_SER_REVANCHA PRIMARY KEY 
        (TITULO_AVENTURA_ANT, NUMERO_MUNDO_ANT, 
            NUMERO_NIVEL_ANT, NOMBRE_JEFE_ANT,
            DIFICULTAD_ANT),
    CONSTRAINT UK_SER_REVANCHA UNIQUE (TITULO_AVENTURA_REV, 
            NUMERO_MUNDO_REV, NUMERO_NIVEL_REV, 
            NOMBRE_JEFE_REV, DIFICULTAD_REV),
    CONSTRAINT FK_SER_REVANCHA_ANT FOREIGN KEY 
        (TITULO_AVENTURA_ANT, NUMERO_MUNDO_ANT, 
            NUMERO_NIVEL_ANT, NOMBRE_JEFE_ANT,
            DIFICULTAD_ANT)
        REFERENCES DESAFIAR_EN (TITULO_AVENTURA, NUMERO_MUNDO, 
            NUMERO_NIVEL, NOMBRE_JEFE, DIFICULTAD),
    CONSTRAINT FK_SER_REVANCHA_REV FOREIGN KEY 
        (TITULO_AVENTURA_REV, NUMERO_MUNDO_REV, 
            NUMERO_NIVEL_REV, NOMBRE_JEFE_REV, 
            DIFICULTAD_REV)
        REFERENCES DESAFIAR_EN (TITULO_AVENTURA, NUMERO_MUNDO, 
            NUMERO_NIVEL, NOMBRE_JEFE, DIFICULTAD)
);

CREATE TABLE SER_BONIFICACION
(
    TITULO_AVENTURA VARCHAR2(60) NOT NULL,
    NUMERO_MUNDO NUMBER(3) NOT NULL,
    NUMERO_NIVEL NUMBER(3) NOT NULL,
    NOMBRE_JEFE VARCHAR2(60) NOT NULL,
    DIFICULTAD NUMBER(1) NOT NULL,
    CODIGO_OBJETO VARCHAR2(4) NOT NULL,
    CANTIDAD NUMBER(3),
    CONSTRAINT PK_SER_BONIFICACION PRIMARY KEY 
        (TITULO_AVENTURA, NUMERO_MUNDO, NUMERO_NIVEL, 
            NOMBRE_JEFE, DIFICULTAD, CODIGO_OBJETO),
    CONSTRAINT FK_SER_BONIFICACION_DESAF FOREIGN KEY 
        (TITULO_AVENTURA, NUMERO_MUNDO, 
            NUMERO_NIVEL, NOMBRE_JEFE, DIFICULTAD)
        REFERENCES DESAFIAR_EN (TITULO_AVENTURA, NUMERO_MUNDO, 
            NUMERO_NIVEL, NOMBRE_JEFE, DIFICULTAD),
    CONSTRAINT FK_SER_BONIFICACION_OBJ FOREIGN KEY 
        (CODIGO_OBJETO)
        REFERENCES OBJETOS (CODIGO)
);
