-------------------------|
--DML - JOSE VALERA 1ºDAM|
-------------------------|


INSERT INTO PAISES
(NOMBRE, SEGUIDORES, CRITICA)
VALUES
('ESPAÑA', 60000, 7.86);

INSERT INTO PAISES
VALUES
('ALEMANIA', 4000, 4.45);

INSERT INTO PAISES
VALUES
('JAPON', 900000, 8.98);


INSERT INTO PAISES
VALUES
('ESTADOS UNIDOS', 400000, 6.5);


INSERT INTO PAISES
VALUES
('PORTUGAL', 40000, 4.05);

---------------------------------------------------------------------------------------------


INSERT INTO PLATAFORMAS
(NOMBRE, POTENCIA)
VALUES
('GAME BOY', 10.8);

INSERT INTO PLATAFORMAS
VALUES
('NES', 11.6634);

INSERT INTO PLATAFORMAS
VALUES
('SNES', 14.4534);

INSERT INTO PLATAFORMAS
VALUES
('NINTENDO 64', 93.75);

INSERT INTO PLATAFORMAS
VALUES
('WII', 729);

INSERT INTO PLATAFORMAS
VALUES
('NINTENDO 3DS', 804);

---------------------------------------------------------------------------------------------


INSERT INTO AVENTURAS
(TITULO,PORTADA, ANYO, DESCRIPCION, OBJETIVO, IMPLEMENTACION, TITULO_REMAKE)
VALUES
('SUPER MARIO BROS.', 'SuperMarioBros.png', 1985, SUBSTR(UPPER('Super Mario Bros. tiene lugar en el pacífico Reino Champiñón (Kinoko Okoku, Mushroom Kingdom en la versión en inglés), donde viven hongos antropomorfos, que fue invadido por los Koopa, una tribu de tortugas. El tranquilo pueblo es convertido en piedra y ladrillos, y el reino de los champiñones se va a la ruina. La única que puede deshacer el influjo mágico de ellos es la Princesa Peach, hija del Rey Champiñón. Desafortunadamente, está en las garras del Rey Tortuga Koopa, Bowser.'), 1, 250), UPPER('EVITAR QUE PUEDAN RAPTAR PRINCESAS y MATAR a los invasores Koopas del reino.'), NULL, NULL);

INSERT INTO AVENTURAS
VALUES
('MARIO BROS.', 'MarioBros.png', 1983, UPPER('Mario es retratado como un fontanero ítalo-estadounidense que, junto con su hermano menor Luigi, tiene que MATAR a las criaturas que han venido de las alcantarillas debajo de Nueva York. El juego se centra en la exterminación de ellos, volteándolos sobre sus espaldas y PATEARLOS.'), UPPER('MATAR A TODOS LOS ENEMIGOS Y EVITAR QUE PUEDAN DESTROZAR TODO'), NULL, NULL);

INSERT INTO AVENTURAS
VALUES
('SUPER MARIO BROS. 2', 'SuperMarioBros2.png', 1988, 'TRATA DE SALVAR A LA PRINCESA POR SEGUNDA VEZ, CON MÁS ENEMIGOS Y PODERES ACOMPAÑANDO A MARIO', 'SALVAR A LA PRINCESA OTRA VEZ Y EVITAR LOS ATAQUES DE BOWSER', NULL, NULL);

INSERT INTO AVENTURAS
VALUES
('SUPER MARIO BROS. 3', 'SuperMarioBros3.png', 1989, 'TRATA DE SALVAR A LA PRINCESA POR TERCERA VEZ', 'SALVAR A LA PRINCESA', NULL, NULL);

INSERT INTO AVENTURAS
VALUES
('SUPER MARIO LAND', 'SuperMarioLand.png', 1989, 'TRATA DE SALVAR A LA DAISY VIAJANDO POR EL MUNDO', 'SALVAR A LA DAISY', NULL, NULL);

INSERT INTO AVENTURAS
VALUES
('SUPER MARIO 3D LAND', 'SuperMario3DLand.png', 2012, 'TRATA DE SALVAR A LA DAISY VIAJANDO POR EL MUNDO', 'SALVAR A LA DAISY', 'EFECTOS Y ANIMACIÓN 3D', 'SUPER MARIO LAND');

INSERT INTO AVENTURAS
VALUES
('SUPER MARIO 64', 'SuperMario64.png', 1997, 'RESUELVE EL SECUESTRO DE PEACH VIAJANDO POR EL MUNDO DE LOS CUADROS', 'RESCATAR A PEACH Y DEVOLVER LA VIDA A SU CASTILLO', NULL, NULL);

INSERT INTO AVENTURAS
VALUES
('SUPER MARIO WORLD', 'SuperMarioWorld.png', 1990, 'Después de salvar el Mushroom Kingdom, los hermanos Mario y Luigi acuerdan irse de vacaciones a un lugar llamado «Dinosaur Land», donde habitan diversos tipos de dinosaurios.', 'Salvar a la Princesa Toadstool y a los amigos dinosaurios de Yoshi.', NULL, NULL);

INSERT INTO AVENTURAS
VALUES
('SUPER MARIO WORLD 2 (YOSHIS ISLAND)', 'SuperMarioWorld2YoshisIsland.png', 1995, 'La historia empieza con Kamek, un malvado Magikoopa que quiere secuestrar a Baby Mario y Baby Luigi. Tras un ligero error de cálculo, Kamek falla y solo se lleva a Baby Luigi y Baby Mario cae a la isla de los Yoshis (Yoshis Island, el primer escenario del mundo Dinosaur Land en Super Mario World).', 'Un Yoshi verde al encontrarlo en su camino decide devolverlo a su familia.', NULL, NULL);

INSERT INTO AVENTURAS
VALUES
('SUPER MARIO 3D WORLD', 'SuperMario3DWorld.png', 2013, 'Mario y sus amigos están disfrutando de una fantástica noche de fuegos artificiales en el Reino Champiñón cuando se encuentran con una misteriosa tubería de cristal, ¡y una princesa hada muy nerviosa!. Poco tardan en enterarse de que Bowser ha hecho de las suyas.', ' Mario, Luigi, Peach y Toad se lanzan por la tubería hasta el Reino Feri para salvarla.', 'ADAPTACIÓN DE LOS ESCENARIOS Y NIVELES A LA JUGABILIDAD 3D', 'SUPER MARIO WORLD');


-----------------------------------------------------------------------------------------------


INSERT INTO CREARSE_PARA
(TITULO_AVENTURA, NOMBRE_PLATAFORMA)
SELECT TITULO, NOMBRE
FROM AVENTURAS, PLATAFORMAS
WHERE (TITULO IN ('SUPER MARIO BROS.','MARIO BROS.') AND NOMBRE IN ('NES','GAME BOY', 'NINTENDO 3DS')) OR
    (TITULO = 'SUPER MARIO BROS. 2' AND NOMBRE IN ('NES','SNES','NINTENDO 3DS','GAME BOY')) OR
    (TITULO = 'SUPER MARIO BROS. 3' AND NOMBRE IN ('NES','SNES','NINTENDO 3DS')) OR
    (TITULO = 'SUPER MARIO LAND' AND NOMBRE IN ('GAME BOY','NINTENDO 3DS')) OR
    (TITULO = 'SUPER MARIO 3D LAND' AND NOMBRE IN ('NINTENDO 3DS')) OR
    (TITULO = 'SUPER MARIO 64' AND NOMBRE IN ('NINTENDO 64')) OR
    (TITULO IN ('SUPER MARIO WORLD 2 (YOSHIS ISLAND)','SUPER MARIO WORLD') AND NOMBRE IN ('GAME BOY','SNES')) OR
    (TITULO = 'SUPER MARIO 3D WORLD' AND NOMBRE = 'WII');

INSERT INTO SALIR_EN
(NOMBRE_PAIS, TITULO_AVENTURA, NOMBRE_PLATAFORMA, FECHA_SALIDA)
SELECT P.NOMBRE, C.TITULO_AVENTURA, C.NOMBRE_PLATAFORMA, CASE WHEN P.NOMBRE = 'JAPON' THEN TO_DATE(A.ANYO, 'YYYY') ELSE TO_DATE(A.ANYO + 1, 'YYYY') END
FROM CREARSE_PARA C, PAISES P, AVENTURAS A
WHERE A.TITULO = C.TITULO_AVENTURA;

------------------------------------------------------------------------------------------------

INSERT INTO ESCENARIO
(NOMBRE,DESCRIPCION)
VALUES
('CASTILLO PEACH VILLA CHAMPIÑON','CASTILLO MITICO DE SUPER MARIO 64, MUY IMPORTANTE');

INSERT INTO ESCENARIO
(NOMBRE,DESCRIPCION)
VALUES
('CAMPO ABIERTO REINO CHAMPIÑON','ESCENARIO MUY COMUN EN LAS AVENTURAS');

INSERT INTO ESCENARIO
(NOMBRE,DESCRIPCION)
VALUES
('AFUERAS DEL REINO','ESCENARIO MUY COMUN EN LAS AVENTURAS');

INSERT INTO ESCENARIO
(NOMBRE,DESCRIPCION)
VALUES
('MANSIÓN BOO','ESCENARIO MUY COMUN EN LAS AVENTURAS');

------------------------------------------------------------------------------------------------
--DROP TABLE TMP_NUMBERS
CREATE TABLE TMP_NUMBERS
(
    NUMERO NUMBER(2) NULL
);

INSERT INTO TMP_NUMBERS VALUES (1);
INSERT INTO TMP_NUMBERS VALUES (2);
INSERT INTO TMP_NUMBERS VALUES (3);
INSERT INTO TMP_NUMBERS VALUES (4);
INSERT INTO TMP_NUMBERS VALUES (5);
INSERT INTO TMP_NUMBERS VALUES (6);
INSERT INTO TMP_NUMBERS VALUES (7);
INSERT INTO TMP_NUMBERS VALUES (8);

INSERT INTO MUNDOS
(TITULO_AVENTURA,NUMERO,NOMBRE_ESCENARIO,TEMATICA)
SELECT A.TITULO, N.NUMERO, CASE WHEN MOD(N.NUMERO, 3) = 0 THEN 'MANSIÓN BOO' WHEN MOD(N.NUMERO, 2) = 0 THEN 'AFUERAS DEL REINO' WHEN N.NUMERO = 1 THEN 'CASTILLO PEACH VILLA CHAMPIÑON' ELSE 'CAMPO ABIERTO REINO CHAMPIÑON' END, 
    CASE WHEN MOD(N.NUMERO, 3) = 0 THEN 'MANSION ENCANTADA' WHEN MOD(N.NUMERO, 2) = 0 THEN 'ACUATICO' WHEN N.NUMERO = 1 THEN 'CASTILLO' ELSE 'CAMPO ABIERTO' END
FROM AVENTURAS A, TMP_NUMBERS N;

INSERT INTO TMP_NUMBERS VALUES (9);
INSERT INTO TMP_NUMBERS VALUES (10);

INSERT INTO NIVELES
(TITULO_AVENTURA, NUMERO_MUNDO, NUMERO, NOMBRE)
SELECT M.TITULO_AVENTURA, M.NUMERO, N.NUMERO, 'NIVEL ' || M.NUMERO || '-' || N.NUMERO
FROM MUNDOS M, TMP_NUMBERS N;

INSERT INTO MISIONES
(TITULO_AVENTURA, NUMERO_MUNDO, NUMERO_NIVEL, DURACION_MAX,TIPO)
SELECT TITULO_AVENTURA, NUMERO_MUNDO, NUMERO, CASE WHEN NUMERO_MUNDO * NUMERO > 10 THEN 6000 ELSE 500 END, CASE WHEN NUMERO_MUNDO * NUMERO > 10 AND MOD(NUMERO_MUNDO,2) = 0 AND NUMERO_MUNDO != 10 THEN 'ACUATICO' ELSE 'TERRESTRE' END
FROM NIVELES
WHERE NUMERO NOT IN (3, 6);

INSERT INTO BONUS
(TITULO_AVENTURA, NUMERO_MUNDO, NUMERO_NIVEL)
SELECT TITULO_AVENTURA, NUMERO_MUNDO, NUMERO
FROM NIVELES
WHERE NUMERO IN (3, 6);

INSERT INTO NIVEL_JEFE
(TITULO_AVENTURA, NUMERO_MUNDO, NUMERO_NIVEL, "FINAL", FORMA)
SELECT TITULO_AVENTURA, NUMERO_MUNDO, NUMERO_NIVEL, CASE WHEN NUMERO_MUNDO = 8 AND NUMERO_NIVEL = 10 THEN 1 ELSE 0 END, CASE WHEN NUMERO_NIVEL = 5 THEN 'BARCO' ELSE 'CASTILLO' END
FROM MISIONES
WHERE NUMERO_NIVEL IN (5, 10);

INSERT INTO PUNTOS_GUARDADO
(TITULO_AVENTURA,NUMERO_MUNDO,NUMERO_NIVEL,NUMERO)
SELECT TITULO_AVENTURA, NUMERO_MUNDO, NUMERO_NIVEL, NUMERO
FROM MISIONES, TMP_NUMBERS
WHERE NUMERO IN(1, 2);

INSERT INTO META
(TITULO_AVENTURA,NUMERO_MUNDO,NUMERO_NIVEL,NUMERO_GUARDADO)
SELECT TITULO_AVENTURA, NUMERO_MUNDO, NUMERO_NIVEL, NUMERO
FROM PUNTOS_GUARDADO 
WHERE MOD(NUMERO_NIVEL, 2) = 0
    OR NUMERO = 2;


/*
INSERT INTO DESBLOQUEAR
(TITULO_AVENTURA_META, NUMERO_MUNDO_META, NUMERO_NIVEL_META, 
    NUMERO_GUARDADO_META, TITULO_AVENTURA_NIVEL, NUMERO_MUNDO_NIVEL,
    NUMERO_NIVEL)
SELECT TITULO_AVENTURA, NUMERO_MUNDO, NUMERO_NIVEL, NUMERO_GUARDADO,
    TITULO_AVENTURA, CASE WHEN NUMERO_NIVEL = 10 AND NUMERO_MUNDO != 8 THEN NUMERO_MUNDO + 1 WHEN NUMERO_NIVEL = 10 AND NUMERO_MUNDO = 8 THEN 1 ELSE NUMERO_MUNDO END,
    CASE WHEN NUMERO_NIVEL = 10 THEN 1 ELSE NUMERO_NIVEL + 1 END
FROM META;
*/

------------------------------------------------------------------------------------------------

INSERT INTO OBJETOS
(CODIGO, NOMBRE)
VALUES
('MON1', 'MONEDA COMÚN');

INSERT INTO OBJETOS
VALUES
('MON2', 'MONEDA ROJA');

INSERT INTO OBJETOS
VALUES
('MON3', 'MONEDA AZUL');

INSERT INTO OBJETOS
VALUES
('MON4', 'MONEDA GIGANTE');

INSERT INTO OBJETOS
VALUES
('MON5', 'MONEDA INVISIBLE');

INSERT INTO OBJETOS
VALUES
('CHA1', 'CHAMPIÑÓN COMÚN');

INSERT INTO OBJETOS
VALUES
('CHA2', 'CHAMPIÑÓN GIGANTE');

INSERT INTO OBJETOS
VALUES
('CHA3', 'MINI CHAMPIÑÓN');

INSERT INTO OBJETOS
VALUES
('CHA4', 'CHAMPIÑÓN VIDA');

INSERT INTO OBJETOS
VALUES
('FLO1', 'FLOR DE FUEGO');

INSERT INTO OBJETOS
VALUES
('FLO2', 'FLOR DE HIELO');

INSERT INTO OBJETOS
VALUES
('FLO3', 'FLOR DE NUBE');

INSERT INTO OBJETOS
VALUES
('FLO4', 'FLOR DORADA');

INSERT INTO OBJETOS
VALUES
('ALA1', 'ALAS');

INSERT INTO OBJETOS
VALUES
('EST1', 'SUPER ESTRELLA');

INSERT INTO OBJETOS
VALUES
('COL1', 'ENERGILUNA');

INSERT INTO OBJETOS
VALUES
('COL2', 'MONEDA SECRETA');

INSERT INTO OBJETOS
VALUES
('COL3', 'PARCHES');

INSERT INTO OBJETOS
VALUES
('COL4', 'JOYA SECRETA');

-------------------------------------------------------------------------------------------------


INSERT INTO ENCONTRARSE_EN
(CODIGO_OBJETO,TITULO_AVENTURA,NUMERO_MUNDO,NUMERO_NIVEL,CANTIDAD)
SELECT O.CODIGO,N.TITULO_AVENTURA,N.NUMERO_MUNDO,N.NUMERO, 
    CASE WHEN N.TITULO_AVENTURA IN('MARIO BROS.') AND O.CODIGO = 'CHA1' THEN 1
        WHEN N.TITULO_AVENTURA IN('SUPER MARIO BROS.','SUPER MARIO BROS. 2') AND O.CODIGO = 'CHA1' THEN 15
        WHEN N.TITULO_AVENTURA IN('SUPER MARIO BROS.','SUPER MARIO BROS. 2') AND O.CODIGO = 'CHA4' THEN 5
        WHEN N.TITULO_AVENTURA IN('SUPER MARIO BROS.','SUPER MARIO BROS. 2') AND O.CODIGO = 'FLO1' THEN 10
        WHEN N.TITULO_AVENTURA IN('SUPER MARIO BROS.','SUPER MARIO BROS. 2') AND O.CODIGO = 'EST1' THEN 1
        WHEN N.TITULO_AVENTURA = 'SUPER MARIO BROS. 2' AND O.CODIGO = 'CHA2' THEN 1
        WHEN N.TITULO_AVENTURA IN('SUPER MARIO BROS. 3','SUPER MARIO WORLD','SUPER MARIO WORLD 2 (YOSHIS ISLAND)','SUPER MARIO 3D WORLD') AND O.CODIGO = 'CHA1' THEN 20
        WHEN N.TITULO_AVENTURA IN('SUPER MARIO BROS. 3','SUPER MARIO WORLD','SUPER MARIO WORLD 2 (YOSHIS ISLAND)','SUPER MARIO 3D WORLD') AND O.CODIGO = 'CHA4' THEN 5
        WHEN N.TITULO_AVENTURA IN('SUPER MARIO BROS. 3','SUPER MARIO WORLD','SUPER MARIO WORLD 2 (YOSHIS ISLAND)','SUPER MARIO 3D WORLD') AND O.CODIGO = 'FLO1' THEN 15
        WHEN N.TITULO_AVENTURA = 'SUPER MARIO BROS. 3' AND O.CODIGO = 'ALA1' THEN 10
        WHEN N.TITULO_AVENTURA IN('SUPER MARIO BROS. 3','SUPER MARIO WORLD','SUPER MARIO WORLD 2 (YOSHIS ISLAND)','SUPER MARIO 3D WORLD') AND O.CODIGO = 'EST1' THEN 1
        WHEN N.TITULO_AVENTURA IN('SUPER MARIO WORLD','SUPER MARIO 3D WORLD') AND O.CODIGO = 'ALA1' THEN 3
        WHEN N.TITULO_AVENTURA IN('SUPER MARIO LAND','SUPER MARIO 3D LAND') AND O.CODIGO = 'CHA1' THEN 15
        WHEN N.TITULO_AVENTURA IN('SUPER MARIO LAND','SUPER MARIO 3D LAND') AND O.CODIGO = 'FLO1' THEN 8
        WHEN N.TITULO_AVENTURA IN('SUPER MARIO LAND','SUPER MARIO 3D LAND') AND O.CODIGO = 'EST1' THEN 1
        WHEN N.TITULO_AVENTURA = 'SUPER MARIO 3D LAND' AND O.CODIGO = 'FLO2' THEN 5
        WHEN N.TITULO_AVENTURA = 'SUPER MARIO 64' AND O.CODIGO = 'EST1' THEN 1
        WHEN N.TITULO_AVENTURA = 'SUPER MARIO 64' AND O.CODIGO = 'CHA2' THEN 1
        WHEN N.TITULO_AVENTURA = 'SUPER MARIO 64' AND O.CODIGO = 'ALA1' THEN 7
        WHEN N.TITULO_AVENTURA = 'SUPER MARIO 3D WORLD' AND O.CODIGO = 'CHA3' THEN 4
        WHEN N.TITULO_AVENTURA = 'SUPER MARIO 3D WORLD' AND O.CODIGO = 'FLO2' THEN 6
        WHEN N.TITULO_AVENTURA = 'SUPER MARIO 3D WORLD' AND O.CODIGO = 'FLO4' THEN 1
        ELSE 1 END CANTIDAD
FROM NIVELES N, OBJETOS O
WHERE (N.TITULO_AVENTURA != 'SUPER MARIO 64' AND O.CODIGO ='CHA1') OR 
    (N.TITULO_AVENTURA IN('SUPER MARIO BROS. 2','SUPER MARIO 64') AND O.CODIGO = 'CHA2') OR
    (N.TITULO_AVENTURA = 'SUPER MARIO 3D WORLD' AND O.CODIGO = 'CHA3') OR
    (N.TITULO_AVENTURA IN('SUPER MARIO BROS.','SUPER MARIO BROS. 2','SUPER MARIO BROS. 3','SUPER MARIO WORLD','SUPER MARIO WORLD 2 (YOSHIS ISLAND)','SUPER MARIO 3D WORLD','SUPER MARIO 64') AND O.CODIGO = 'CHA4') OR
    (N.TITULO_AVENTURA != 'SUPER MARIO 64' AND O.CODIGO = 'FLO1') OR
    (N.TITULO_AVENTURA = 'SUPER MARIO 3D WORLD' AND O.CODIGO IN('FLO2','FLO3')) OR
    (N.TITULO_AVENTURA IN('SUPER MARIO BROS. 3','SUPER MARIO WORLD','SUPER MARIO WORLD 2 (YOSHIS ISLAND)','SUPER MARIO 3D WORLD','SUPER MARIO 64') AND O.CODIGO = 'ALA1') OR
    (N.TITULO_AVENTURA != 'MARIO BROS.' AND O.CODIGO = 'EST1');

-------------------------------------------------------------------------------------------------


INSERT INTO PERSONAJES 
(NOMBRE_JAP, NOMBRE_ESP, NOMBRE_ING,IMAGEN, RAZA, BONDAD, NOMBRE_JAP_VERSION)
VALUES 
('RUIJI', 'LUIGI', 'LUIGI', 'Luigi.png', 'HUMANA', 'B', NULL);

INSERT INTO PERSONAJES 
VALUES 
('PICHI-HIME', 'PRINCESA PEACH', 'PEACH PRINCESS', 'Peach.png', 'HUMANA', 'B', NULL);

INSERT INTO PERSONAJES 
VALUES 
('YOSSHI', 'YOSHI', 'YOSHI', 'Yoshi.png', 'YOSHI', 'B', NULL);

--------------------------------------------------------------------------------------------------------

INSERT INTO PERSONAJES 
VALUES 
('PICHI-HIME-AKACHAN', 'PRINCESA BEBÉ', 'BABY PEACH', 'BabyPeach.png', 'HUMANA', 'B', 'PICHI-HIME');

INSERT INTO PERSONAJES 
VALUES 
('RUIJI-AKACHAN', 'LUIGI BEBÉ', 'BABY LUIGI', 'BabyLuigi.png', 'HUMANA', 'B', 'RUIJI');

INSERT INTO PERSONAJES 
VALUES 
('KINOPIKO', 'TOADETTE', 'TOADETTE', 'Toadette.png', 'TOAD', 'B', NULL);

INSERT INTO PERSONAJES 
VALUES 
('KINOPIO', 'TOAD', 'TOAD', 'Toad.png', 'TOAD', 'B', NULL);

INSERT INTO PERSONAJES 
VALUES 
('DEIJI-HIME', 'PRINCESA DAISY', 'DAISY PRINCESS', 'Daisy.png', 'HUMANA', 'B', NULL);

INSERT INTO PERSONAJES 
VALUES 
('DEIJI-HIME-AKACHAN', 'DAISY BEBÉ', 'BABY DAISY', 'BabyDaisy.png', 'HUMANA', 'B', 'DEIJI-HIME');

-------------------------------------------------------------------------------------------------------------

INSERT INTO PERSONAJES 
VALUES 
('BOB-OMB', 'BOB-OMB', 'BOB-OMB', 'bobomb.png', 'BobOmb.png', 'M', NULL);

INSERT INTO PERSONAJES 
VALUES 
('KURIBO', 'GOOMBA', 'GOOMBA', 'goomba.png', 'Goomba.png', 'M', NULL);

INSERT INTO PERSONAJES 
VALUES 
('NOKONOKO', 'KOOPA TROOPA', 'KOOPA TROOPA', 'KoopaTroopa.png', 'KOOPA', 'M', NULL);

INSERT INTO PERSONAJES 
VALUES 
('PATAPATA', 'KOOPA PARATROOPA', 'KOOPA PARATROOPA', 'KoopaParatroopa.png', 'KOOPA', 'M', NULL);

INSERT INTO PERSONAJES 
VALUES 
('KOOPA', 'BOWSER', 'BOWSER', 'Bowser.png', 'KOOPA', 'M', NULL);


-------------------------------------------------------------------------------------------------------------------


INSERT INTO PERSONAJES 
VALUES 
('KOOPA-HONE', 'BOWSITOS', 'DRY BOWSER', 'Bowsitos.png', 'KOOPA', 'M', 'KOOPA');

INSERT INTO PERSONAJES 
VALUES 
('KOOPA-JUNIA', 'BOWSY', 'BOWSER JR.', 'Bowsy.png', 'KOOPA', 'M', NULL);

INSERT INTO PERSONAJES 
VALUES 
('BOB-OMB-KINGU', 'REY BOB-OMB', 'BOB-OMB KING', 'BobOmbKing.png', 'BOB-OMB', 'M', NULL);

INSERT INTO PERSONAJES 
VALUES 
('KURIBO-KINGU', 'REY GOOMBA', 'GOOMBA KING', 'GoombaKing.png', 'GOOMBA', 'M', NULL);

------------------------------------------------------------------------------------------------------------------

INSERT INTO HABILIDADES 
(NOMBRE)
VALUES
('VIDA EXTRA');

INSERT INTO HABILIDADES 
(NOMBRE)
VALUES
('TOQUE EXTRA');

INSERT INTO HABILIDADES 
(NOMBRE)
VALUES
('INCREMENTO TAMAÑO');

INSERT INTO HABILIDADES 
(NOMBRE)
VALUES
('INVULNERABILIDAD');

------------------------------------------------------------------------------------------------------------------
INSERT INTO PERSONAJES 
VALUES 
('JUGEMU', 'LAKITU', 'LAKITU', 'lakitu.png', 'KOOPA', 'N', NULL);

INSERT INTO MONEDAS
(CODIGO_OBJETO, VALOR)
SELECT CODIGO, CASE WHEN SUBSTR(CODIGO, -1) = 1 THEN  1 WHEN SUBSTR(CODIGO, -1) = 2 THEN 5 WHEN SUBSTR(CODIGO, -1) = 3 THEN 25 WHEN SUBSTR(CODIGO, -1) = 4 THEN 50  WHEN SUBSTR(CODIGO, -1) = 5 THEN 100 END
FROM OBJETOS 
WHERE CODIGO LIKE 'MON%';

INSERT INTO COLECCIONABLES
(CODIGO_OBJETO)
SELECT CODIGO
FROM OBJETOS 
WHERE CODIGO LIKE 'COL%';

INSERT INTO POWER_UPS
(CODIGO_OBJETO)
SELECT CODIGO
FROM OBJETOS 
WHERE CODIGO NOT LIKE 'COL%' AND CODIGO NOT LIKE 'MON%';

INSERT INTO TEMPORALES
(CODIGO_OBJETO)
VALUES
('EST1');

INSERT INTO BENEFICIOSOS
(CODIGO_OBJETO)
SELECT CODIGO_OBJETO
FROM POWER_UPS;

INSERT INTO PROPORCIONAR
(CODIGO_OBJETO_BENEFICIOSO, NOMBRE_HABILIDAD, IMPLEMENTACION) 
VALUES
('CHA4', 'VIDA EXTRA', 1);

INSERT INTO PROPORCIONAR 
(CODIGO_OBJETO_BENEFICIOSO, NOMBRE_HABILIDAD, IMPLEMENTACION) 
VALUES
('CHA2', 'INCREMENTO TAMAÑO', 5);

INSERT INTO PROPORCIONAR
(CODIGO_OBJETO_BENEFICIOSO, NOMBRE_HABILIDAD, IMPLEMENTACION)
SELECT CODIGO_OBJETO, NOMBRE, 1
FROM BENEFICIOSOS B, HABILIDADES H
WHERE CODIGO_OBJETO IN ('CHA1', 'FLO1', 'FLO2', 'FLO3', 'FLO4') AND NOMBRE IN ('TOQUE EXTRA', 'INCREMENTO TAMAÑO');

INSERT INTO PROPORCIONAR
(CODIGO_OBJETO_BENEFICIOSO, NOMBRE_HABILIDAD, IMPLEMENTACION)
SELECT CODIGO_OBJETO, NOMBRE, 3
FROM BENEFICIOSOS B, HABILIDADES H
WHERE CODIGO_OBJETO IN ('EST1', 'CHA2') AND NOMBRE IN ('INVULNERABILIDAD');

INSERT INTO REINO
(NOMBRE_JAP, NOMBRE_REINO)
SELECT NOMBRE_JAP, CASE WHEN RAZA IN ('HUMANA', 'TOAD') THEN 'REINO CHAMPIÑON' WHEN RAZA = ('KOOPA') THEN 'REINO BOWSER'  WHEN RAZA = ('BOB-OMB') THEN 'REINO BOB-OMB' ELSE NULL END
FROM PERSONAJES
WHERE RAZA IN ('HUMANA', 'TOAD','KOOPA','BOB-OMB');

INSERT INTO TENER_POSICION_SUPERIOR
(NOMBRE_PERSONAJE_SUPERIOR, NOMBRE_PERSONAJE_INFERIOR)
SELECT S.NOMBRE_JAP, I.NOMBRE_JAP
FROM REINO S, REINO I
WHERE S.NOMBRE_REINO = I.NOMBRE_REINO
    AND ((INSTR(S.NOMBRE_JAP, 'KINGU') > 0 AND INSTR(I.NOMBRE_JAP, 'KINGU') <= 0)
    OR (INSTR(S.NOMBRE_JAP, 'SAKACHAN') <= 0 AND INSTR(I.NOMBRE_JAP, 'SAKACHAN') > 0));

INSERT INTO JEFE
(NOMBRE_JAP)
SELECT NOMBRE_JAP
FROM PERSONAJES
WHERE INSTR(NOMBRE_ESP, 'REY') > 0 OR INSTR(NOMBRE_ESP, 'BOW') > 0;

INSERT INTO DESAFIAR_EN
(TITULO_AVENTURA,NUMERO_MUNDO,NUMERO_NIVEL,NOMBRE_JEFE,DIFICULTAD)
SELECT N.TITULO_AVENTURA, N.NUMERO_MUNDO, N.NUMERO_NIVEL, J.NOMBRE_JAP, 8
FROM JEFE J,NIVEL_JEFE N
WHERE (MOD(N.NUMERO_MUNDO, 2) = 0 AND J.NOMBRE_JAP = 'KOOPA') 
    OR (MOD(N.NUMERO_MUNDO, 4) = 0 AND J.NOMBRE_JAP = 'KOOPA-HONE');

INSERT INTO DESAFIAR_EN
(TITULO_AVENTURA,NUMERO_MUNDO,NUMERO_NIVEL,NOMBRE_JEFE,DIFICULTAD)
SELECT N.TITULO_AVENTURA, N.NUMERO_MUNDO, N.NUMERO_NIVEL, J.NOMBRE_JAP, 5
FROM JEFE J,NIVEL_JEFE N
WHERE MOD(N.NUMERO_MUNDO, 2) != 0 AND J.NOMBRE_JAP = 'KOOPA-JUNIA';

INSERT INTO SER_BONIFICACION
(TITULO_AVENTURA, NUMERO_MUNDO, NUMERO_NIVEL, NOMBRE_JEFE, DIFICULTAD, CODIGO_OBJETO, CANTIDAD)
SELECT TITULO_AVENTURA, NUMERO_MUNDO, NUMERO_NIVEL, NOMBRE_JEFE, DIFICULTAD, CODIGO_OBJETO, CASE WHEN NOMBRE_JEFE = 'KOOPA' THEN 50 WHEN NOMBRE_JEFE = 'KOOPA-HONE' THEN 150 ELSE 20 END
FROM DESAFIAR_EN D, MONEDAS M
WHERE CODIGO_OBJETO = 'MON1';

DELETE FROM SER_BONIFICACION
WHERE TITULO_AVENTURA = 'SUPER MARIO BROS. 3'
    AND NUMERO_MUNDO = 4
    AND NUMERO_NIVEL = 5
    AND  NOMBRE_JEFE IN ('KOOPA', 'KOOPA-HONE');
    
DELETE FROM SER_BONIFICACION
WHERE TITULO_AVENTURA = 'SUPER MARIO BROS. 2'
    AND NUMERO_MUNDO = 4
    AND NUMERO_NIVEL = 5
    AND  NOMBRE_JEFE = 'KOOPA';

UPDATE SER_BONIFICACION
SET CANTIDAD = 80
WHERE TITULO_AVENTURA = 'SUPER MARIO BROS. 2'
    AND NUMERO_MUNDO IN (4,8)
    AND NUMERO_NIVEL = 5
    AND  NOMBRE_JEFE = 'KOOPA-HONE';
    
INSERT INTO SER_REVANCHA
(TITULO_AVENTURA_ANT, NUMERO_MUNDO_ANT, NUMERO_NIVEL_ANT, 
    NOMBRE_JEFE_ANT, DIFICULTAD_ANT, TITULO_AVENTURA_REV, 
    NUMERO_MUNDO_REV, NUMERO_NIVEL_REV, NOMBRE_JEFE_REV, 
    DIFICULTAD_REV)
SELECT ANT.TITULO_AVENTURA, ANT.NUMERO_MUNDO, ANT.NUMERO_NIVEL, ANT.NOMBRE_JEFE, ANT.DIFICULTAD, 
    REV.TITULO_AVENTURA, REV.NUMERO_MUNDO, REV.NUMERO_NIVEL, REV.NOMBRE_JEFE, REV.DIFICULTAD
FROM DESAFIAR_EN ANT, DESAFIAR_EN REV
WHERE ANT.TITULO_AVENTURA = REV.TITULO_AVENTURA
 AND ANT.NUMERO_MUNDO = REV.NUMERO_MUNDO
 AND ANT.NUMERO_NIVEL = REV.NUMERO_NIVEL
 AND ANT.NOMBRE_JEFE = 'KOOPA'
 AND REV.NOMBRE_JEFE = 'KOOPA-HONE';
 
 INSERT INTO APARECER 
 (BANDO, NOMBRE_PERSONAJE, TITULO_AVENTURA)
 SELECT BONDAD, NOMBRE_JAP, TITULO FROM PERSONAJES, AVENTURAS
 WHERE ((NOMBRE_ESP LIKE '%BEB%' OR NOMBRE_ESP IN('YOSHI','BOWSY')) AND TITULO = 'SUPER MARIO WORLD 2 (YOSHIS ISLAND)') OR
    (NOMBRE_ESP IN('LUIGI', 'PRINCESA PEACH', 'YOSHI', 'TOAD') AND TITULO NOT IN( 'SUPER MARIO WORLD 2 (YOSHIS ISLAND)', 'MARIO BROS.')) OR
    (NOMBRE_ESP = ('BOWSER') AND TITULO != 'MARIO BROS.') OR
    (NOMBRE_ESP IN ('BOWSITOS','BOWSY','GOOMBA') AND ANYO >= 1990) OR
    NOMBRE_ESP IN ('KOOPA TROOPA') OR
    (BONDAD = 'M' AND ANYO >= 2010) OR
    (NOMBRE_ESP = 'PRINCESA DAISY' AND TITULO = 'SUPER MARIO LAND');
 
INSERT INTO SER_COMPATIBLE 
(NOMBRE_PERSONAJE,CODIGO_OBJETO_BENEFICIOSO,TITULO_AVENTURA)
SELECT NOMBRE_PERSONAJE,CODIGO_OBJETO,TITULO_AVENTURA FROM APARECER, BENEFICIOSOS
WHERE (CODIGO_OBJETO IN ('CHA1','CHA4') AND BANDO = 'B') OR
    (CODIGO_OBJETO LIKE 'FLO%' AND NOMBRE_PERSONAJE IN ('RUIJI','PICHI-HIME','KINOPIO')) OR
    (CODIGO_OBJETO IN ('FLO1','EST1') AND NOMBRE_PERSONAJE IN ('KOOPA','KOOPA-HONE') AND TITULO_AVENTURA IN('SUPER MARIO 3D WORLD','SUPER MARIO 3D LAND')) OR
    (CODIGO_OBJETO LIKE 'ALA%' AND NOMBRE_PERSONAJE = 'RUIJI') OR
    (CODIGO_OBJETO LIKE 'EST%' AND NOMBRE_PERSONAJE IN ('RUIJI','PICHI-HIME')) OR
    (CODIGO_OBJETO = 'CHA2' AND NOMBRE_PERSONAJE IN ('NOKONOKO','KURIBO') AND TITULO_AVENTURA ='SUPER MARIO 64');