CREATE GLOBAL TEMPORARY TABLE TMP_AVENTURAS_LISTADO
(
    TITULO VARCHAR2(60),
    PAISES_LISTA VARCHAR2(200),
    PAISES_CAL_SUP NUMBER(2),
    PLATAFORMAS_LISTA VARCHAR2(200),
    CANTIDAD_MUNDOS NUMBER(2),
    CANTIDAD_NIVELES NUMBER(3),
    NUMERO_ALIADOS NUMBER(3),
    NUMERO_ENEMIGOS NUMBER(3)
) ON COMMIT PRESERVE ROWS; --drop table TMP_AVENTURAS_LISTADO;

CREATE GLOBAL TEMPORARY TABLE TMP_OBJETOS_COMPATIBLES
(
    TITULO_AVENTURA VARCHAR2(60),
    OBJETOS_COMPATIBLES VARCHAR2(2000)
) ON COMMIT PRESERVE ROWS; --drop table TMP_OBJETOS_COMPATIBLES;

CREATE GLOBAL TEMPORARY TABLE TMP_OBJETOS_HAB
(
    COD_NOMBRE VARCHAR2(70),
    HABILIDADES VARCHAR2(300)
) ON COMMIT PRESERVE ROWS; --drop table TMP_OBJETOS_HAB;

CREATE GLOBAL TEMPORARY TABLE TMP_AVENTURAS_BUSQUEDA
(
    TITULO_AVENTURA VARCHAR2(60),
    PORTADA VARCHAR2(100),
    ANYO NUMBER(4),
    DESCRIPCION VARCHAR2(300),
    OBJETIVO VARCHAR2(100),
    IMPLEMENTACION VARCHAR2(200),
    TITULO_REMAKE VARCHAR2(60),
    PLATAFORMAS_LISTA VARCHAR2(400),
    OBJETOS_LISTA VARCHAR2(500),
    PERSONAJES_LISTA VARCHAR2(700),
    INDICE_ORDEN NUMBER(5)
) ON COMMIT PRESERVE ROWS; --drop table TMP_AVENTURAS_BUSQUEDA;
